### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by ya332** [amaan-ahmad/screenx#1]
Hello Amaan,
great job with the project. How did you manage to get the audio working? Audio doesn't work for me.

**Comment by amaan-ahmad** [comment]
Hi @ya332 ,

It seems to be working for me.
Can you please let me know about your system software specifications?

Primarily:  
- Operating System 
- Browser and it's version number

Thanks.

**Comment by ya332** [comment]
Windows 11 64 bit and Chrome Version 98.0.4758.102 (Official Build) (64-bit).

**Comment by amaan-ahmad** [comment]
even I am using the same software specification. 
Did you check-marked the share audio option before sharing the screen? 

![image](https://user-images.githubusercontent.com/27350808/155840145-ce50fe8e-c839-49cc-87aa-e5e95be967bc.png)

**Comment by ya332** [comment]
Yeah I did.

**Comment by amaan-ahmad** [comment]
@ya332 just released an update with some audio and download fixes. Try again :)

**Comment by ya332** [comment]
Hello @amaan-ahmad I tried it and still not working. :(

**Comment by amaan-ahmad** [comment]
@ya332 are you trying to capture the microphone audio? because it won't work as of now.

**Comment by ya332** [comment]
@amaan-ahmad I was trying to capture much audio. Thanks for letting me know. We can close the issue then.
